name: quality-checks

on: [push]

jobs:
  pylint-flake8-black-mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: pip install -r dev_requirements.txt
    - name: Analysing the code with pylint
      run: pylint $(git ls-files '*.py')
    - name: Analysing the code with mypy
      run: mypy $(git ls-files '*.py')
    - name: Analysing the code with black
      run: black --check $(git ls-files '*.py')
    - name: Analysing the code with flake8
      run: flake8 $(git ls-files '*.py')
